
.. _core-developers-team:


.. raw:: html

    <div class="team-grid">

    <div class="team-member">
        <img
        src="https://avatars.githubusercontent.com/u/6051075?v=4"
        alt="Avatar picture of @plaresmedima"
        class="team-avatar"
        />
        <a href="https://github.com/plaresmedima" class="team-name">Steven Sourbron</a>
        <div class="team-handle">@plaresmedima</div>
    </div>

    <div class="team-member">
        <img
        src="https://avatars.githubusercontent.com/u/64839879?v=4"
        alt="Avatar picture of @kteh123"
        class="team-avatar"
        />
        <a href="https://github.com/kteh123" class="team-name">Kevin Teh</a>
        <div class="team-handle">@kteh123</div>
    </div>

    <!-- Add more team members here -->
    </div>
